server:
  port: 8000
spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:migration/mysql
  #    locations: classpath:db/migration
  datasource:
    url: @jdbc.connection.url@
    driver-class-name: @jdbc.driver.class@
    username: @jdbc.connection.user@
    password: @jdbc.connection.password@